language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - tip

os:
  - linux
  - osx

sudo: false

services:
  # github.com/kenorld/egret/cache
  - memcache
  - redis-server

before_install:
  # TRAVIS_OS_NAME - linux and osx
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install memcached redis; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then nohup /usr/local/opt/memcached/bin/memcached & fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then nohup redis-server /usr/local/etc/redis.conf & fi'

install:
  # Setting environments variables
  - export PATH=$PATH:$HOME/gopath/bin
  - export EGRET_BRANCH="develop"
  - 'if [[ "$TRAVIS_BRANCH" == "master" ]]; then export EGRET_BRANCH="master"; fi'
  - 'echo "Travis branch: $TRAVIS_BRANCH, Egret dependency branch: $EGRET_BRANCH"'
  - go get -v github.com/kenorld/egret/...
  - rm -rf ../config
  - git clone -b $EGRET_BRANCH git://github.com/kenorld/egret/extra/modules ../modules/
  - git clone -b $EGRET_BRANCH git://github.com/kenorld/egret/cmd ../cm
  
  
  
  
  d/
  - git clone -b $EGRET_BRANCH git://github.com/kenorld/egret/conf ../config/
  - git clone -b $EGRET_BRANCH git://github.com/kenorld/egret/corn../cron/
  - git clone git://github.com/kenorld/egret/samples ../samples/
  - go get -v github.com/kenorld/egret/cmd/egret

script:
  - go test -v github.com/kenorld/egret...

  # Ensure the new-app flow works (plus the other commands).
  - egret version
  - egret new     my/testapp
  - egret test    my/testapp
  - egret clean   my/testapp
  - egret build   my/testapp build/testapp
  - egret build   my/testapp build/testapp prod
  - egret package my/testapp
  - egret package my/testapp prod

  # Build & run the sample apps
  - egret test github.com/kenorld/egret/samples/booking
  - egret test github.com/kenorld/egret/samples/chat
  - egret test github.com/kenorld/egret/samples/facebook-oauth2
  - egret test github.com/kenorld/egret/samples/twitter-oauth
  - egret test github.com/kenorld/egret/samples/validation
  - egret test github.com/kenorld/egret/samples/upload

  # Commented out persona test sample, since persona.org gonna be shutdown.
  # Also http://personatestuser.org becomes non-responsive most of the time.
  # https://wiki.mozilla.org/Identity/Persona_Shutdown_Guidelines_for_Reliers
  # - egret test github.com/kenorld/egret/samples/persona

matrix:
  allow_failures:
    - go: tip
