{
  "name": "Egret",
  "secret": "c59946sWnCM2STIjFeSlbLw6T60TECGApDDINSfvxSXepCeGqMhriQqYujpobhyX",
  "serve": {
    "network": "tcp",
    "addr": "",
    "port": 9090,
    "tls": {
      "enabled": false
    },
    "letsencrypt": {
      "enabled": true,
      "cache_dir": ""
    }
  },
  "cookie": {
    "http_only": false,
    "prefix": "EJECT",
    "secure": false,
    "expires": "720h"
  },
  "format": {
    "date": "01/22/2006",
    "datetime": "01/22/2006 15:04"
  },
  "template": {
    "native": {
      "enabled": true,
      "extensions": ".html",
      "root": "/",
      "layout": ""
    },
    "markdown": {
      "enabled": true,
      "extensions": ".md,.markdown"
    }
  },
  "render": {
    "chunked": false,
    "compressed": true
  },
  "[dev]": {
    "dev_mode": true,
    "serve": {
      "letsencrypt": {
        "enabled": false
      }
    },
    "render": {
      "pretty": true
    },
    "watch": {
      "enabled": true,
      "mode": "normal"
    },
    "log": {
      "output": "stderr",
      "level": "info"
    }
  },
  "[prod]": {
    "dev_mode": false,
    "pretty": false,
    "watch": {
      "enabled": false
    },
    "log": {
      "output": "%(app.name).log",
      "level": "info"
    }
  }
}